/* eslint-disable no-unused-vars */
import React, { useState } from "react";
import * as elems from "./2fa.styles";

import { TwoFaCodeField, TwoFaOtpField } from "./TwoFaField.jsx";
import { SubmitButton } from "../AccountSecurity.jsx";

import { Content, TextInner } from "../AccountSecurity.jsx";
import GooglePlay from "../../../../../../assets/svg/profile/Store download button-2.svg";
import AppStore from "../../../../../../assets/svg/profile/Store download button.svg";
import QR from "../../../../../../assets/svg/profile/QR Code.svg";
import DoneIcon from "../../../../../../assets/svg/profile/Done.svg";

const TwoFa = () => {
  return (
    <>
      <Content>
        <TextInner style={{ maxWidth: "800px" }}>
          Two-Factor Authentication (2FA) adds an extra layer of security to
          your account. Instead of relying solely on a password, a 2FA login
          code can be generated via a text message, an app on a phone or another
          personal device, or even a dedicated physical device. This makes it
          much harder for anyone to access your account, even if they somehow
          manage to obtain your password.
        </TextInner>
      </Content>
      <elems.SettingsSection>
        <elems.StepWrapper>
          <elems.NumberedCircle>1</elems.NumberedCircle>
          {/* Блок з двома текстами */}
          <elems.StepTextContent>
            <elems.StepTitle>
              Download the Google Authenticator app
            </elems.StepTitle>
            <elems.StepDescription>
              Download the Google Authenticator app from the Google Play Store
              or App Store using the buttons below.
            </elems.StepDescription>
          </elems.StepTextContent>
        </elems.StepWrapper>
        <elems.StoreBadgesWrapper>
          <AppStore
            style={{
              width: "120px",
              height: "40px",
              objectFit: "contain",
              cursor: "pointer",
            }}
          />
          <GooglePlay
            style={{
              width: "120px",
              height: "40px",
              objectFit: "contain",
              cursor: "pointer",
            }}
          />
        </elems.StoreBadgesWrapper>
      </elems.SettingsSection>
      <elems.SettingsSection>
        <elems.StepWrapper>
          <elems.NumberedCircle>2</elems.NumberedCircle>
          {/* Блок з двома текстами */}
          <elems.StepTextContent>
            <elems.StepTitle>
              Connect your account with Google Authenticator
            </elems.StepTitle>
            <elems.StepDescription>
              Scan the QR code or copy the code below and paste it into the
              required field in the app.
            </elems.StepDescription>
          </elems.StepTextContent>
        </elems.StepWrapper>
        <QR></QR>
        <TwoFaCodeField />
      </elems.SettingsSection>
      <elems.SettingsSection>
        <elems.StepWrapper>
          <elems.NumberedCircle>3</elems.NumberedCircle>
          {/* Блок з двома текстами */}
          <elems.StepTextContent>
            <elems.StepTitle>
              Enter the code generated by the Google Authenticator app here
            </elems.StepTitle>
            <elems.StepDescription>
              After scanning the QR code or entering the code above into the
              application, enter the code generated by the application here to
              complete the process.
            </elems.StepDescription>
          </elems.StepTextContent>
        </elems.StepWrapper>
        <TwoFaOtpField />
        <SubmitButton style={{ maxWidth: "600px" }} type="submit">
          Send the code <DoneIcon />
        </SubmitButton>
      </elems.SettingsSection>
    </>
  );
};

export default TwoFa;
